version: '3'

services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - env/.env.${APP_ENV}
    networks: 
      - nodeapp-network
  
  mongodb:
    image: mongo
    networks:
      - nodeapp-network
  
networks:
  nodeapp-network:
    driver: bridge